Этапы эксперимента:
1. генерация подклассов матриц ТВ, ТН, БП, БЛ q=4
2. генерация подклассов k=q^b
3. генерация последовательностей 5 последовательностей B=5
4. функция расчета вектора a (метод рабинера)
5. формирование датасета b^k векторов

In [ ]:
import quantecon as qe
import numpy as np
import pandas as pd

In [ ]:
tv = np.array([[0.25, 0.25, 0.25, 0.25], 
      [1/3,   1/3,  1/3,  0], 
      [0.5,   0.5,   0,   0],
      [0.5,   0,     0,   0.5]])

tn = np.array( [[0.5,  0,     0,    0.5], 
      [0,    0,     0.5,  0.5],
      [0,    1/3,   1/3,  1/3],
      [0.25, 0.25, 0.25, 0.25]])

bp =  np.array( [[0,      0,    0.5,   0.5],
                [0,      0,     0.5,   0.5],
                [0.5,    0.5,   0,    0], 
                [0.5,    0.5,   0,    0]])

bl =   np.array([[0.5,    0.5, 0,    0], 
      [0.5,    0.5,  0,    0],
      [0,      0,    0.5,   0.5],
      [0,      0,    0.5,   0.5]])

In [ ]:
tvt=[*zip(*tv)]
tvt

[(0.25, 0.3333333333333333, 0.5, 0.5),
 (0.25, 0.3333333333333333, 0.5, 0.0),
 (0.25, 0.3333333333333333, 0.0, 0.0),
 (0.25, 0.0, 0.0, 0.5)]

In [ ]:
tvt=np.array(tvt)
tvt


array([[0.25      , 0.33333333, 0.5       , 0.5       ],
       [0.25      , 0.33333333, 0.5       , 0.        ],
       [0.25      , 0.33333333, 0.        , 0.        ],
       [0.25      , 0.        , 0.        , 0.5       ]])

In [ ]:
pi=[[1/4,    1/4,  1/4,    1/4]]
pi


[[0.25, 0.25, 0.25, 0.25]]

In [ ]:
from itertools import *

In [ ]:
#комбинации классов 
for i in combinations_with_replacement(['tv','tn','bp','pl'], 4):
    print(i, end=' ') # aa ab ac ad bb bc bd cc cd dd 

('tv', 'tv', 'tv', 'tv') ('tv', 'tv', 'tv', 'tn') ('tv', 'tv', 'tv', 'bp') ('tv', 'tv', 'tv', 'pl') ('tv', 'tv', 'tn', 'tn') ('tv', 'tv', 'tn', 'bp') ('tv', 'tv', 'tn', 'pl') ('tv', 'tv', 'bp', 'bp') ('tv', 'tv', 'bp', 'pl') ('tv', 'tv', 'pl', 'pl') ('tv', 'tn', 'tn', 'tn') ('tv', 'tn', 'tn', 'bp') ('tv', 'tn', 'tn', 'pl') ('tv', 'tn', 'bp', 'bp') ('tv', 'tn', 'bp', 'pl') ('tv', 'tn', 'pl', 'pl') ('tv', 'bp', 'bp', 'bp') ('tv', 'bp', 'bp', 'pl') ('tv', 'bp', 'pl', 'pl') ('tv', 'pl', 'pl', 'pl') ('tn', 'tn', 'tn', 'tn') ('tn', 'tn', 'tn', 'bp') ('tn', 'tn', 'tn', 'pl') ('tn', 'tn', 'bp', 'bp') ('tn', 'tn', 'bp', 'pl') ('tn', 'tn', 'pl', 'pl') ('tn', 'bp', 'bp', 'bp') ('tn', 'bp', 'bp', 'pl') ('tn', 'bp', 'pl', 'pl') ('tn', 'pl', 'pl', 'pl') ('bp', 'bp', 'bp', 'bp') ('bp', 'bp', 'bp', 'pl') ('bp', 'bp', 'pl', 'pl') ('bp', 'pl', 'pl', 'pl') ('pl', 'pl', 'pl', 'pl') 

In [ ]:
mc1 = qe.MarkovChain(tv)

print(mc1)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.25       0.25       0.25       0.25      ]
 [0.33333333 0.33333333 0.33333333 0.        ]
 [0.5        0.5        0.         0.        ]
 [0.5        0.         0.         0.5       ]]>


In [ ]:
#симулиция последовательности, длина 1000
a2=mc1.simulate(10, random_state=None)
display(a2)

array([1, 0, 2, 1, 0, 0, 2, 0, 1, 0])

In [ ]:
#симулиция последовательности, длина 1000
a1=mc1.simulate(10, random_state=None)
a2=mc1.simulate(10, random_state=None)
a3=mc1.simulate(10, random_state=None)
a4=mc1.simulate(10, random_state=None)
a5=mc1.simulate(10, random_state=None)
a6=mc1.simulate(10, random_state=None)
a7=mc1.simulate(10, random_state=None)
a8=mc1.simulate(10, random_state=None)
a9=mc1.simulate(10, random_state=None)
a10=mc1.simulate(10, random_state=None)

In [ ]:
array=np.column_stack((a1, a2,a3,a4,a5,a6,a7,a8,a9,a10))

In [ ]:
df = pd.DataFrame(array)

df[0]=[2,0,1,0,3,3,0,2,1,1]
display(df.head(20))

0  1  2  3  4  5  6  7  8  9
0  2  0  2  3  0  0  2  1  0  3
1  0  2  0  0  3  0  0  0  2  0
2  1  0  1  3  3  3  2  1  0  1
3  0  3  1  0  0  3  1  1  0  2
4  3  0  2  2  2  0  1  1  2  0
5  3  1  0  0  1  2  1  0  0  2
6  0  0  2  3  0  1  2  3  1  0
7  2  0  1  3  2  2  0  3  2  1
8  1  2  0  3  0  0  1  0  1  0
9  1  0  0  3  1  0  1  2  2  1

Пусть ('tv', 'tn', 'tn', 'bp')

In [ ]:
#Расчет вектора альфа методом Рабинера
alfa= np.zeros((10, 4))


alfa


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:

beta=np.array([[0.0,0.0,0.0,0.0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0]])

beta

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
pi=np.array([1/4,    1/4,  1/4,    1/4])
pi

array([0.25, 0.25, 0.25, 0.25])

In [ ]:
 df[0].iloc[1:]


1    0
2    1
3    0
4    3
5    3
6    0
7    2
8    1
9    1
Name: 0, dtype: int64

In [ ]:
k=df.loc[0][0]    
k
pi[k]
alfa[0,2]=pi[k]
alfa

array([[0.  , 0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ]])

In [ ]:
tvt

array([[0.25      , 0.33333333, 0.5       , 0.5       ],
       [0.25      , 0.33333333, 0.5       , 0.        ],
       [0.25      , 0.33333333, 0.        , 0.        ],
       [0.25      , 0.        , 0.        , 0.5       ]])

In [ ]:
alfa[0]

array([0.  , 0.  , 0.25, 0.  ])

In [ ]:
ii=[0,1,2,3,4,5,6,7,8,9]
j=1
v=0
b=0
for d in ii:
    for b in ii:
        k=df.loc[b][d]  
        print(k)
    
 
    
    

In [ ]:

def vecalfa(n):
    alfa= np.zeros((10, 4))
    k=df.loc[0][n]    
    print(k)
    alfa[0,k]=pi[k]
    print(alfa[0])
   
    j=1
    for i in df[n].iloc[1:]:    

        alfa[j,i]=np.dot(alfa[j-1], tvt[i])
        j=j+1

        
    return alfa
          
vecalfa(0)



2
[0.   0.   0.25 0.  ]


array([[0.00000000e+00, 0.00000000e+00, 2.50000000e-01, 0.00000000e+00],
       [1.25000000e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 3.12500000e-02, 0.00000000e+00, 0.00000000e+00],
       [1.04166667e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.60416667e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.30208333e-03],
       [6.51041667e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.62760417e-04, 0.00000000e+00],
       [0.00000000e+00, 8.13802083e-05, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.71267361e-05, 0.00000000e+00, 0.00000000e+00]])

In [ ]:
ii=[0,1,2,3,4,5,6,7,8,9]

for d in ii:
        vecalfa(d)
        print(alfa) 
        

2
[0.   0.   0.25 0.  ]
[[2.50000000e-01 0.00000000e+00 2.50000000e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.25000000e-02 0.00000000e+00]
 [0.00000000e+00 3.12500000e-02 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.04166667e-02 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.47222222e-03 0.00000000e+00 0.00000000e+00]
 [1.15740741e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.89351852e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.44675926e-04]
 [7.23379630e-05 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.80844907e-05]]
0
[0.25 0.   0.   0.  ]
[[2.50000000e-01 0.00000000e+00 2.50000000e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.25000000e-02 0.00000000e+00]
 [0.00000000e+00 3.12500000e-02 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.04166667e-02 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.47222222e-03 0.00000000e+00 0.00000000e+00]
 [1.15

In [ ]:
alfadf = pd.DataFrame(alfa)
alfadf


0         1         2         3
0  0.250000  0.250000  0.250000  0.250000
1  0.395833  0.270833  0.000000  0.187500
2  0.203125  0.109375  0.189236  0.192708
3  0.278212  0.167969  0.000000  0.147135
4  0.000000  0.094510  0.103190  0.143121
5  0.154659  0.043584  0.000000  0.001302
6  0.051050  0.017964  0.053193  0.000000
7  0.020468  0.045347  0.006151  0.000000
8  0.013947  0.000081  0.020233  0.000000
9  0.007197  0.013630  0.000000  0.001172

In [ ]:
alfadf['type'] = pd.Series([1,1,1,1,1,1,1,1,1,1])
alfadf

0         1         2         3  type
0  0.250000  0.250000  0.250000  0.250000     1
1  0.395833  0.270833  0.000000  0.187500     1
2  0.203125  0.109375  0.189236  0.192708     1
3  0.278212  0.167969  0.000000  0.147135     1
4  0.000000  0.094510  0.103190  0.143121     1
5  0.154659  0.043584  0.000000  0.001302     1
6  0.051050  0.017964  0.053193  0.000000     1
7  0.020468  0.045347  0.006151  0.000000     1
8  0.013947  0.000081  0.020233  0.000000     1
9  0.007197  0.013630  0.000000  0.001172     1

In [ ]:
ii=[0,1,2,3,4,5,6,7,8,9]
j=1
for d in ii:
   
    for i in df[d].iloc[1:]:    

        alfa[j,i]=np.dot(alfa[j-1], tvt[i])
        j=j+1
    d=d+1   
alfa   


In [ ]:
import numpy as np
 
class MarkovChain(object):
    def __init__(self, transition_prob):
        """
        Initialize the MarkovChain instance.
 
        Parameters
        ----------
        transition_prob: dict
            A dict object representing the transition 
            probabilities in Markov Chain. 
            Should be of the form: 
                {'state1': {'state1': 0.1, 'state2': 0.4}, 
                 'state2': {...}}
        """
        self.transition_prob = transition_prob
        self.states = list(transition_prob.keys())
 
    def next_state(self, current_state):
        """
        Returns the state of the random variable at the next time 
        instance.
 
        Parameters
        ----------
        current_state: str
            The current state of the system.
        """
        next_ = np.random.choice(self.states, p = [
              self.transition_prob[current_state][next_state] 
               for next_state in self.states]
        )
        return next_
 
    def generate_states(self, current_state, no=10):
        """
        Generates the next states of the system.
 
        Parameters
        ----------
        current_state: str
            The state of the current random variable.
 
        no: int
            The number of future states to generate.
        """
        future_states = []
        for i in range(no):
            next_state = self.next_state(current_state)
            future_states.append(next_state)
            current_state = next_state

        return ''.join(future_states)

In [ ]:
def MarkovMatrix(n = 26):
  '''
  Generates a Markov matrix for transition among n symbols
  
  Parameters
  ----------
  n: int
      number of symbols
  '''

  np.random.seed(0) # for replicability
  symbols = [chr(i+65) for i in range(n)] # list of available symbols

  markov_matrix = {}
  for i, s in enumerate(symbols):
    dim = len(symbols)

    # Probabilities of change of state (symbol)
    # Random with a decreasing probability to jump to the farthest states
    # It could be replaced by a negative logarithmic function  to make it more 
    # likely to land in the same state and change the complexity of the sequence
    probs = np.random.random(dim*3) 
    probs.sort()
    probs = np.append(probs[dim%2::2], probs[::-2])
    offset = -int(dim*1.5)
    # to keep the highest value in the current state
    probs = np.roll(probs, offset+i)[:dim] 
    probs /= probs.sum()
    
    markov_matrix[s] = {s: p for s, p in zip(symbols, probs)}

  return markov_matrix